/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthedRouteImport } from './routes/admin._authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin._authed.index'
import { Route as AdminAuthedWorkshopsRouteImport } from './routes/admin._authed.workshops'
import { Route as AdminAuthedVolunteersRouteImport } from './routes/admin._authed.volunteers'
import { Route as AdminAuthedTestimonialsRouteImport } from './routes/admin._authed.testimonials'
import { Route as AdminAuthedTeamRouteImport } from './routes/admin._authed.team'
import { Route as AdminAuthedSupportRouteImport } from './routes/admin._authed.support'
import { Route as AdminAuthedShopRouteImport } from './routes/admin._authed.shop'
import { Route as AdminAuthedSettingsRouteImport } from './routes/admin._authed.settings'
import { Route as AdminAuthedLecturesRouteImport } from './routes/admin._authed.lectures'
import { Route as AdminAuthedKnowledgeBaseRouteImport } from './routes/admin._authed.knowledge-base'
import { Route as AdminAuthedIntegrationLogsRouteImport } from './routes/admin._authed.integration-logs'
import { Route as AdminAuthedInquiriesRouteImport } from './routes/admin._authed.inquiries'
import { Route as AdminAuthedGalleryRouteImport } from './routes/admin._authed.gallery'
import { Route as AdminAuthedFaqRouteImport } from './routes/admin._authed.faq'
import { Route as AdminAuthedEventsRouteImport } from './routes/admin._authed.events'
import { Route as AdminAuthedDonationsRouteImport } from './routes/admin._authed.donations'
import { Route as AdminAuthedContentRouteImport } from './routes/admin._authed.content'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedWorkshopsRoute = AdminAuthedWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedVolunteersRoute = AdminAuthedVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedTestimonialsRoute = AdminAuthedTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedTeamRoute = AdminAuthedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedSupportRoute = AdminAuthedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedShopRoute = AdminAuthedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedSettingsRoute = AdminAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedLecturesRoute = AdminAuthedLecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedKnowledgeBaseRoute =
  AdminAuthedKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedIntegrationLogsRoute =
  AdminAuthedIntegrationLogsRouteImport.update({
    id: '/integration-logs',
    path: '/integration-logs',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedInquiriesRoute = AdminAuthedInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedGalleryRoute = AdminAuthedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedFaqRoute = AdminAuthedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedEventsRoute = AdminAuthedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDonationsRoute = AdminAuthedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedContentRoute = AdminAuthedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/volunteers': typeof VolunteersRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/content': typeof AdminAuthedContentRoute
  '/admin/donations': typeof AdminAuthedDonationsRoute
  '/admin/events': typeof AdminAuthedEventsRoute
  '/admin/faq': typeof AdminAuthedFaqRoute
  '/admin/gallery': typeof AdminAuthedGalleryRoute
  '/admin/inquiries': typeof AdminAuthedInquiriesRoute
  '/admin/integration-logs': typeof AdminAuthedIntegrationLogsRoute
  '/admin/knowledge-base': typeof AdminAuthedKnowledgeBaseRoute
  '/admin/lectures': typeof AdminAuthedLecturesRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/shop': typeof AdminAuthedShopRoute
  '/admin/support': typeof AdminAuthedSupportRoute
  '/admin/team': typeof AdminAuthedTeamRoute
  '/admin/testimonials': typeof AdminAuthedTestimonialsRoute
  '/admin/volunteers': typeof AdminAuthedVolunteersRoute
  '/admin/workshops': typeof AdminAuthedWorkshopsRoute
  '/admin/': typeof AdminAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/volunteers': typeof VolunteersRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/content': typeof AdminAuthedContentRoute
  '/admin/donations': typeof AdminAuthedDonationsRoute
  '/admin/events': typeof AdminAuthedEventsRoute
  '/admin/faq': typeof AdminAuthedFaqRoute
  '/admin/gallery': typeof AdminAuthedGalleryRoute
  '/admin/inquiries': typeof AdminAuthedInquiriesRoute
  '/admin/integration-logs': typeof AdminAuthedIntegrationLogsRoute
  '/admin/knowledge-base': typeof AdminAuthedKnowledgeBaseRoute
  '/admin/lectures': typeof AdminAuthedLecturesRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/shop': typeof AdminAuthedShopRoute
  '/admin/support': typeof AdminAuthedSupportRoute
  '/admin/team': typeof AdminAuthedTeamRoute
  '/admin/testimonials': typeof AdminAuthedTestimonialsRoute
  '/admin/volunteers': typeof AdminAuthedVolunteersRoute
  '/admin/workshops': typeof AdminAuthedWorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/volunteers': typeof VolunteersRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/_authed/content': typeof AdminAuthedContentRoute
  '/admin/_authed/donations': typeof AdminAuthedDonationsRoute
  '/admin/_authed/events': typeof AdminAuthedEventsRoute
  '/admin/_authed/faq': typeof AdminAuthedFaqRoute
  '/admin/_authed/gallery': typeof AdminAuthedGalleryRoute
  '/admin/_authed/inquiries': typeof AdminAuthedInquiriesRoute
  '/admin/_authed/integration-logs': typeof AdminAuthedIntegrationLogsRoute
  '/admin/_authed/knowledge-base': typeof AdminAuthedKnowledgeBaseRoute
  '/admin/_authed/lectures': typeof AdminAuthedLecturesRoute
  '/admin/_authed/settings': typeof AdminAuthedSettingsRoute
  '/admin/_authed/shop': typeof AdminAuthedShopRoute
  '/admin/_authed/support': typeof AdminAuthedSupportRoute
  '/admin/_authed/team': typeof AdminAuthedTeamRoute
  '/admin/_authed/testimonials': typeof AdminAuthedTestimonialsRoute
  '/admin/_authed/volunteers': typeof AdminAuthedVolunteersRoute
  '/admin/_authed/workshops': typeof AdminAuthedWorkshopsRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/donations'
    | '/events'
    | '/gallery'
    | '/privacy'
    | '/shop'
    | '/terms'
    | '/volunteers'
    | '/workshops'
    | '/admin/login'
    | '/api/chat'
    | '/admin/content'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/integration-logs'
    | '/admin/knowledge-base'
    | '/admin/lectures'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/support'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/volunteers'
    | '/admin/workshops'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/donations'
    | '/events'
    | '/gallery'
    | '/privacy'
    | '/shop'
    | '/terms'
    | '/volunteers'
    | '/workshops'
    | '/admin/login'
    | '/api/chat'
    | '/admin/content'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/integration-logs'
    | '/admin/knowledge-base'
    | '/admin/lectures'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/support'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/volunteers'
    | '/admin/workshops'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/donations'
    | '/events'
    | '/gallery'
    | '/privacy'
    | '/shop'
    | '/terms'
    | '/volunteers'
    | '/workshops'
    | '/admin/_authed'
    | '/admin/login'
    | '/api/chat'
    | '/admin/_authed/content'
    | '/admin/_authed/donations'
    | '/admin/_authed/events'
    | '/admin/_authed/faq'
    | '/admin/_authed/gallery'
    | '/admin/_authed/inquiries'
    | '/admin/_authed/integration-logs'
    | '/admin/_authed/knowledge-base'
    | '/admin/_authed/lectures'
    | '/admin/_authed/settings'
    | '/admin/_authed/shop'
    | '/admin/_authed/support'
    | '/admin/_authed/team'
    | '/admin/_authed/testimonials'
    | '/admin/_authed/volunteers'
    | '/admin/_authed/workshops'
    | '/admin/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DonationsRoute: typeof DonationsRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyRoute: typeof PrivacyRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  VolunteersRoute: typeof VolunteersRoute
  WorkshopsRoute: typeof WorkshopsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/workshops': {
      id: '/admin/_authed/workshops'
      path: '/workshops'
      fullPath: '/admin/workshops'
      preLoaderRoute: typeof AdminAuthedWorkshopsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/volunteers': {
      id: '/admin/_authed/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminAuthedVolunteersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/testimonials': {
      id: '/admin/_authed/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminAuthedTestimonialsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/team': {
      id: '/admin/_authed/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAuthedTeamRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/support': {
      id: '/admin/_authed/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminAuthedSupportRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/shop': {
      id: '/admin/_authed/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminAuthedShopRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/settings': {
      id: '/admin/_authed/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthedSettingsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/lectures': {
      id: '/admin/_authed/lectures'
      path: '/lectures'
      fullPath: '/admin/lectures'
      preLoaderRoute: typeof AdminAuthedLecturesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/knowledge-base': {
      id: '/admin/_authed/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/admin/knowledge-base'
      preLoaderRoute: typeof AdminAuthedKnowledgeBaseRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/integration-logs': {
      id: '/admin/_authed/integration-logs'
      path: '/integration-logs'
      fullPath: '/admin/integration-logs'
      preLoaderRoute: typeof AdminAuthedIntegrationLogsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/inquiries': {
      id: '/admin/_authed/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminAuthedInquiriesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/gallery': {
      id: '/admin/_authed/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminAuthedGalleryRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/faq': {
      id: '/admin/_authed/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminAuthedFaqRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/events': {
      id: '/admin/_authed/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminAuthedEventsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/donations': {
      id: '/admin/_authed/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminAuthedDonationsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/content': {
      id: '/admin/_authed/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminAuthedContentRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedContentRoute: typeof AdminAuthedContentRoute
  AdminAuthedDonationsRoute: typeof AdminAuthedDonationsRoute
  AdminAuthedEventsRoute: typeof AdminAuthedEventsRoute
  AdminAuthedFaqRoute: typeof AdminAuthedFaqRoute
  AdminAuthedGalleryRoute: typeof AdminAuthedGalleryRoute
  AdminAuthedInquiriesRoute: typeof AdminAuthedInquiriesRoute
  AdminAuthedIntegrationLogsRoute: typeof AdminAuthedIntegrationLogsRoute
  AdminAuthedKnowledgeBaseRoute: typeof AdminAuthedKnowledgeBaseRoute
  AdminAuthedLecturesRoute: typeof AdminAuthedLecturesRoute
  AdminAuthedSettingsRoute: typeof AdminAuthedSettingsRoute
  AdminAuthedShopRoute: typeof AdminAuthedShopRoute
  AdminAuthedSupportRoute: typeof AdminAuthedSupportRoute
  AdminAuthedTeamRoute: typeof AdminAuthedTeamRoute
  AdminAuthedTestimonialsRoute: typeof AdminAuthedTestimonialsRoute
  AdminAuthedVolunteersRoute: typeof AdminAuthedVolunteersRoute
  AdminAuthedWorkshopsRoute: typeof AdminAuthedWorkshopsRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedContentRoute: AdminAuthedContentRoute,
  AdminAuthedDonationsRoute: AdminAuthedDonationsRoute,
  AdminAuthedEventsRoute: AdminAuthedEventsRoute,
  AdminAuthedFaqRoute: AdminAuthedFaqRoute,
  AdminAuthedGalleryRoute: AdminAuthedGalleryRoute,
  AdminAuthedInquiriesRoute: AdminAuthedInquiriesRoute,
  AdminAuthedIntegrationLogsRoute: AdminAuthedIntegrationLogsRoute,
  AdminAuthedKnowledgeBaseRoute: AdminAuthedKnowledgeBaseRoute,
  AdminAuthedLecturesRoute: AdminAuthedLecturesRoute,
  AdminAuthedSettingsRoute: AdminAuthedSettingsRoute,
  AdminAuthedShopRoute: AdminAuthedShopRoute,
  AdminAuthedSupportRoute: AdminAuthedSupportRoute,
  AdminAuthedTeamRoute: AdminAuthedTeamRoute,
  AdminAuthedTestimonialsRoute: AdminAuthedTestimonialsRoute,
  AdminAuthedVolunteersRoute: AdminAuthedVolunteersRoute,
  AdminAuthedWorkshopsRoute: AdminAuthedWorkshopsRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

interface AdminRouteChildren {
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  DonationsRoute: DonationsRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  PrivacyRoute: PrivacyRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  VolunteersRoute: VolunteersRoute,
  WorkshopsRoute: WorkshopsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
